package com.cpu.quikdata

const val PREFILLED_DATA_ID = "PREFILLED_DATA_ID"
const val SHARED_PREFS_KEY = "SHARED_PREFS_KEY"
const val DEVICE_ID_KEY = "DEVICE_ID_KEY"

const val FIREBASE_KEY_DEVICES = "devices"

const val FIREBASE_KEY_FORM = "form"
const val FIREBASE_KEY_PREFILLED = "baselineData"
const val FIREBASE_KEY_FORM_DETAILS = "formDetails"

const val FIREBASE_KEY_GENERAL_INFO = "generalInfo"
const val FIREBASE_KEY_CALAMITY_INFO = "calamityInfo"
const val FIREBASE_KEY_POPULATION = "population"
const val FIREBASE_KEY_FAMILIES = "families"
const val FIREBASE_KEY_VULNERABLE = "vulnerable"
const val FIREBASE_KEY_CASUALTIES = "casualties"
const val FIREBASE_KEY_CAUSE_OF_DEATH = "causeOfDeath"
const val FIREBASE_KEY_INFRASTRUCTURE = "infrastructureDamage"

const val FIREBASE_KEY_SHELTER_INFO = "shelterInfo"
const val FIREBASE_KEY_HOUSE_DAMAGE = "houseDamage"
const val FIREBASE_KEY_SHELTER_COPING = "shelterCoping"
const val FIREBASE_KEY_SHELTER_NEEDS = "shelterNeeds"
const val FIREBASE_KEY_SHELTER_ASSISTANCE = "shelterAssistance"
const val FIREBASE_KEY_SHELTER_GAPS = "shelterGaps"

const val FIREBASE_KEY_FOOD_SECURITY = "foodSecurity"
const val FIREBASE_KEY_FOOD_IMPACT = "foodImpact"
const val FIREBASE_KEY_FOOD_COPING = "foodCoping"
const val FIREBASE_KEY_FOOD_NEEDS = "foodNeeds"
const val FIREBASE_KEY_FOOD_ASSISTANCE = "foodAssistance"
const val FIREBASE_KEY_FOOD_GAPS = "foodGaps"

const val FIREBASE_KEY_LIVELIHOODS = "livelihoods"
const val FIREBASE_KEY_INCOME_BEFORE = "incomeBefore"
const val FIREBASE_KEY_INCOME_AFTER = "incomeAfter"
const val FIREBASE_KEY_ESTIMATED_DAMAGE = "estimatedDamage"
const val FIREBASE_KEY_LIVELIHOODS_COPING = "livelihoodsCoping"
const val FIREBASE_KEY_LIVELIHOODS_NEEDS = "livelihoodsNeeds"
const val FIREBASE_KEY_LIVELIHOODS_ASSISTANCE = "livelihoodsAssistance"
const val FIREBASE_KEY_LIVELIHOODS_GAPS = "livelihoodsGaps"

const val FIREBASE_KEY_HEALTH_INFO = "healthInfo"
const val FIREBASE_KEY_DISEASES = "diseases"
const val FIREBASE_KEY_SPECIAL_NEEDS = "specialNeeds"
const val FIREBASE_KEY_PSYCHOSOCIAL = "psychosocial"
const val FIREBASE_KEY_HEALTH_COPING = "healthCoping"
const val FIREBASE_KEY_HEALTH_ASSISTANCE = "healthAssistance"
const val FIREBASE_KEY_HEALTH_GAPS = "healthGaps"

const val FIREBASE_KEY_WASH_INFO = "waterSanitationHygiene"
const val FIREBASE_KEY_WASH_CONDITIONS = "washConditions"
const val FIREBASE_KEY_WASH_COPING = "washCoping"
const val FIREBASE_KEY_WASH_ASSISTANCE = "washAssistance"
const val FIREBASE_KEY_WASH_GAPS = "washGaps"

const val FIREBASE_KEY_EVACUATION = "evacuationSites"
const val FIREBASE_KEY_EVACUATION_SITE_INFO = "evacuationSiteInfo"
const val FIREBASE_KEY_EVACUATION_AGE = "evacuationAge"
const val FIREBASE_KEY_EVACUATION_FACILITIES = "evacuationFacilities"
const val FIREBASE_KEY_EVACUATION_WASH = "evacuationWash"
const val FIREBASE_KEY_EVACUATION_PROTECTION = "evacuationProtection"
const val FIREBASE_KEY_EVACUATION_COPING = "evacuationCoping"